<a href="https://colab.research.google.com/github/t8101349/Colab-/blob/master/0117_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

* 完成後請寄到EMAIL : clement.class.02@gmail.com
* 信件主旨請設定為： 03-02.Pandas_課堂練習_學號_姓名 (例: "03-02.Pandas_課堂練習_00_陳仁政")
* 附件檔名請設定為： 03-02.Pandas_課堂練習_學號_姓名.ipynb (例: "03-02.Pandas_課堂練習_00_陳仁政.ipynb")

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
data = pd.read_csv("/content/vgsales.csv")
data.head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37

In [ ]:
# 找出有缺失值的欄位

data.isnull().sum()
#data.info()

Rank              0
Name              0
Platform          0
Year            271
Genre             0
Publisher        58
NA_Sales          0
EU_Sales          0
JP_Sales          0
Other_Sales       0
Global_Sales      0
dtype: int64

In [ ]:
# 計算欄位的基本統計數據
data.describe()

,Rank,Year,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
count,16598.000000,16327.000000,16598.000000,16598.000000,16598.000000,16598.000000,16598.000000
mean,8300.605254,2006.406443,0.264667,0.146652,0.077782,0.048063,0.537441
std,4791.853933,5.828981,0.816683,0.505351,0.309291,0.188588,1.555028
min,1.000000,1980.000000,0.000000,0.000000,0.000000,0.000000,0.010000
25%,4151.250000,2003.000000,0.000000,0.000000,0.000000,0.000000,0.060000
50%,8300.500000,2007.000000,0.080000,0.020000,0.000000,0.010000,0.170000
75%,12449.750000,2010.000000,0.240000,0.110000,0.040000,0.040000,0.470000
max,16600.000000,2020.000000,41.490000,29.020000,10.220000,10.570000,82.740000

In [ ]:
# 取出 "Publisher" 欄位的資料
data['Publisher']

0          Nintendo
1          Nintendo
2          Nintendo
3          Nintendo
4          Nintendo
            ...
16593         Kemco
16594    Infogrames
16595    Activision
16596      7G//AMES
16597       Wanadoo
Name: Publisher, Length: 16598, dtype: object

In [ ]:
data['Platform']

0        Wii
1        NES
2        Wii
3        Wii
4         GB
        ...
16593    GBA
16594     GC
16595    PS2
16596     DS
16597    GBA
Name: Platform, Length: 16598, dtype: object

In [ ]:
# 取出 Publisher, Name, Genre 欄位的資料
data[['Publisher','Name','Genre']]

,Publisher,Name,Genre
0,Nintendo,Wii Sports,Sports
1,Nintendo,Super Mario Bros.,Platform
2,Nintendo,Mario Kart Wii,Racing
3,Nintendo,Wii Sports Resort,Sports
4,Nintendo,Pokemon Red/Pokemon Blue,Role-Playing
...,...,...,...
16593,Kemco,Woody Woodpecker in Crazy Castle 5,Platform
16594,Infogrames,Men in Black II: Alien Escape,Shooter
16595,Activision,SCORE International Baja 1000: The Official Game,Racing
16596,7G//AMES,Know How 2,Puzzle
16597,Wanadoo,Spirits & Spells,Platform

In [ ]:
# 計算每筆資料的 NA_Sales,EU_Sales,JP_Sales,Other_Sales 總和
data[['NA_Sales','EU_Sales','JP_Sales','Other_Sales']].sum(axis = 1)

0        82.74
1        40.24
2        35.83
3        33.00
4        31.38
         ...
16593     0.01
16594     0.01
16595     0.00
16596     0.01
16597     0.01
Length: 16598, dtype: float64

In [ ]:
# 計算每筆資料的 NA_Sales,EU_Sales,JP_Sales,Other_Sales 總和，並存入新的欄位"總和"
data['total_sales'] = data[['NA_Sales','EU_Sales','JP_Sales','Other_Sales']].sum(axis = 1)
data

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,total_sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82,35.83
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,31.38
...,...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01,0.00
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01,0.01

In [ ]:
#找出發行商為Nintendo的遊戲名稱
isNintendo = data['Publisher'] == 'Nintendo'
data[isNintendo]['Name']

0                                               Wii Sports
1                                        Super Mario Bros.
2                                           Mario Kart Wii
3                                        Wii Sports Resort
4                                 Pokemon Red/Pokemon Blue
                               ...
16269                             Slide Adventure: Mag Kid
16357                 Mario vs. Donkey Kong: Tipping Stars
16456                             Art Academy: Home Studio
16473                                      Captain Rainbow
16542    Mario & Luigi: Paper Jam & Mario Kart 7 Double...
Name: Name, Length: 703, dtype: object

In [ ]:
data[isNintendo]['Name'].nunique()
#data[isNintendo]['Name'].unique().size

667

In [ ]:
#列出所有Wii的遊戲名稱
on_wii = data['Platform'] == 'Wii'
data[on_wii]['Name'].unique()

array(['Wii Sports', 'Mario Kart Wii', 'Wii Sports Resort', ...,
       'Mini Desktop Racing',
       'Yattaman Wii: BikkuriDokkiri Machine de Mou Race da Koron',
       'Fit & Fun'], dtype=object)

In [ ]:
#計算所有GBA遊戲的銷售總合
on_gba = data['Platform'] == 'GBA'
data[on_gba]['Global_Sales'].sum()

318.5

In [ ]:
#計算任天堂運動類遊戲的銷售總量
c1 = data['Publisher'] == 'Nintendo'
c2 = data['Genre'] == 'Sports'
data[c1 & c2]['Global_Sales'].sum()

218.01

In [ ]:
#列出北美地區銷售量最高的前五名遊戲
sort_by_na = data.sort_values(by = 'NA_Sales',ascending = False)
sort_by_na['Name'].head(5)

0           Wii Sports
1    Super Mario Bros.
9            Duck Hunt
5               Tetris
2       Mario Kart Wii
Name: Name, dtype: object

In [ ]:
#列出北美與歐洲地區銷售量總和最高的前五名遊戲
na_eu = data['NA_Sales'] + data['EU_Sales']
data['na_eu_sale'] = na_eu
sort_by_na_eu = data.sort_values(by = 'na_eu_sale',ascending = False)
sort_by_na_eu[:5]['Name']

0           Wii Sports
1    Super Mario Bros.
2       Mario Kart Wii
9            Duck Hunt
3    Wii Sports Resort
Name: Name, dtype: object

In [ ]:
#找出總共有多少種不同的平台
data['Platform'].nunique()

31

In [ ]:
#寫程式計算不同平台的總銷售量
platform = data['Platform'].unique()
for p in platform:
  this_p = data[data['Platform'] == p]
  this_p_sales = this_p['Global_Sales'].sum(axis = 0)
  print(p,this_p_sales)

Wii 926.71
NES 251.07
GB 255.45000000000002
DS 822.49
X360 979.96
PS3 957.84
PS2 1255.6399999999999
SNES 200.05
GBA 318.5
3DS 247.46
PS4 278.1
N64 218.88
PS 730.66
XB 258.26
PC 258.82
2600 97.07999999999998
PSP 296.28000000000003
XOne 141.06
GC 199.35999999999999
WiiU 81.86000000000001
GEN 28.36
DC 15.969999999999999
PSV 61.930000000000014
SAT 33.59
SCD 1.8700000000000003
WS 1.42
NG 1.4400000000000002
TG16 0.16
3DO 0.1
GG 0.04
PCFX 0.03

In [ ]:
# 使用GroupBy來完成上述的工作
group_data = data.groupby('Platform')
group_data['Global_Sales'].sum()

Platform
2600      97.08
3DO        0.10
3DS      247.46
DC        15.97
DS       822.49
GB       255.45
GBA      318.50
GC       199.36
GEN       28.36
GG         0.04
N64      218.88
NES      251.07
NG         1.44
PC       258.82
PCFX       0.03
PS       730.66
PS2     1255.64
PS3      957.84
PS4      278.10
PSP      296.28
PSV       61.93
SAT       33.59
SCD        1.87
SNES     200.05
TG16       0.16
WS         1.42
Wii      926.71
WiiU      81.86
X360     979.96
XB       258.26
XOne     141.06
Name: Global_Sales, dtype: float64

In [9]:
data.groupby('Platform').get_group('Wii')

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
7,8,Wii Play,Wii,2006.0,Misc,Nintendo,14.03,9.20,2.93,2.85,29.02
8,9,New Super Mario Bros. Wii,Wii,2009.0,Platform,Nintendo,14.59,7.06,4.70,2.26,28.62
...,...,...,...,...,...,...,...,...,...,...,...
16517,16520,Teenage Mutant Ninja Turtles,Wii,2007.0,Action,Konami Digital Entertainment,0.00,0.01,0.00,0.00,0.01
16552,16555,Mahou Sensei Negima!? Neo-Pactio Fight!!,Wii,2007.0,Fighting,Marvelous Interactive,0.00,0.00,0.01,0.00,0.01
16573,16576,Mini Desktop Racing,Wii,2007.0,Racing,Popcorn Arcade,0.01,0.00,0.00,0.00,0.01
16574,16577,Yattaman Wii: BikkuriDokkiri Machine de Mou Ra...,Wii,2008.0,Racing,Takara Tomy,0.00,0.00,0.01,0.00,0.01
16581,16584,Fit & Fun,Wii,2011.0,Sports,Unknown,0.00,0.01,0.00,0.00,0.01

In [10]:
data.groupby(['Platform','Publisher'])[['Global_Sales']].sum()

                                                 Global_Sales
Platform Publisher
2600     20th Century Fox Video Games                    1.94
         Activision                                     19.42
         Answer Software                                 0.50
         Atari                                          50.09
         Avalon Interactive                              0.17
...                                                       ...
XOne     Telltale Games                                  0.46
         Tru Blu Entertainment                           0.05
         Ubisoft                                        17.91
         Unknown                                         0.03
         Warner Bros. Interactive Entertainment          9.20

[1801 rows x 1 columns]

In [11]:
keys = ['NA_Sales','EU_Sales','JP_Sales','Other_Sales','Global_Sales']
data.groupby(['Year','Platform'])[keys].sum()

                 NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales
Year   Platform
1980.0 2600         10.59      0.67      0.00         0.12         11.38
1981.0 2600         33.40      1.96      0.00         0.32         35.77
1982.0 2600         26.92      1.65      0.00         0.31         28.86
1983.0 2600          5.44      0.34      0.00         0.06          5.83
       NES           2.32      0.46      8.10         0.08         10.96
...                   ...       ...       ...          ...           ...
2016.0 X360          0.36      0.40      0.00         0.07          0.83
       XOne          6.69      4.63      0.01         1.05         12.37
2017.0 PS4           0.00      0.00      0.03         0.00          0.03
       PSV           0.00      0.00      0.02         0.00          0.02
2020.0 DS            0.27      0.00      0.00         0.02          0.29

[241 rows x 5 columns]

In [12]:
keys = ['NA_Sales','EU_Sales','JP_Sales','Other_Sales','Global_Sales']
data.groupby(['Year','Platform'])[keys].sum().reset_index()

       Year Platform  NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales
0    1980.0     2600     10.59      0.67      0.00         0.12         11.38
1    1981.0     2600     33.40      1.96      0.00         0.32         35.77
2    1982.0     2600     26.92      1.65      0.00         0.31         28.86
3    1983.0     2600      5.44      0.34      0.00         0.06          5.83
4    1983.0      NES      2.32      0.46      8.10         0.08         10.96
..      ...      ...       ...       ...       ...          ...           ...
236  2016.0     X360      0.36      0.40      0.00         0.07          0.83
237  2016.0     XOne      6.69      4.63      0.01         1.05         12.37
238  2017.0      PS4      0.00      0.00      0.03         0.00          0.03
239  2017.0      PSV      0.00      0.00      0.02         0.00          0.02
240  2020.0       DS      0.27      0.00      0.00         0.02          0.29

[241 rows x 7 columns]

In [13]:
# 預設會忽略Nan，可以加上 dropna=False 來強制不忽略
data.groupby('Year',dropna=False).size()

Year
1980.0       9
1981.0      46
1982.0      36
1983.0      17
1984.0      14
1985.0      14
1986.0      21
1987.0      16
1988.0      15
1989.0      17
1990.0      16
1991.0      41
1992.0      43
1993.0      60
1994.0     121
1995.0     219
1996.0     263
1997.0     289
1998.0     379
1999.0     338
2000.0     349
2001.0     482
2002.0     829
2003.0     775
2004.0     763
2005.0     941
2006.0    1008
2007.0    1202
2008.0    1428
2009.0    1431
2010.0    1259
2011.0    1139
2012.0     657
2013.0     546
2014.0     582
2015.0     614
2016.0     344
2017.0       3
2020.0       1
NaN        271
dtype: int64

In [18]:
data.groupby(['Platform','Publisher'])[['Global_Sales']].apply(lambda x: x.mean())

                                                 Global_Sales
Platform Publisher
2600     20th Century Fox Video Games                0.388000
         Activision                                  0.693571
         Answer Software                             0.500000
         Atari                                       0.927593
         Avalon Interactive                          0.170000
...                                                       ...
XOne     Telltale Games                              0.076667
         Tru Blu Entertainment                       0.025000
         Ubisoft                                     0.716400
         Unknown                                     0.030000
         Warner Bros. Interactive Entertainment      0.707692

[1801 rows x 1 columns]

In [19]:
data.groupby(['Platform','Publisher'])[['Global_Sales']].apply(lambda x: x.mean()).reset_index().rename(columns={'Global_Sales': 'globalmeansales'})

     Platform                               Publisher  globalmeansales
0        2600            20th Century Fox Video Games         0.388000
1        2600                              Activision         0.693571
2        2600                         Answer Software         0.500000
3        2600                                   Atari         0.927593
4        2600                      Avalon Interactive         0.170000
...       ...                                     ...              ...
1796     XOne                          Telltale Games         0.076667
1797     XOne                   Tru Blu Entertainment         0.025000
1798     XOne                                 Ubisoft         0.716400
1799     XOne                                 Unknown         0.030000
1800     XOne  Warner Bros. Interactive Entertainment         0.707692

[1801 rows x 3 columns]

In [21]:
x1 = data.groupby('Platform')['Global_Sales'].transform(sum)
x2 = data.groupby('Platform')['Global_Sales'].sum()
print(x1)
print(x2)

0         926.71
1         251.07
2         926.71
3         926.71
4         255.45
          ...
16593     318.50
16594     199.36
16595    1255.64
16596     822.49
16597     318.50
Name: Global_Sales, Length: 16598, dtype: float64
Platform
2600      97.08
3DO        0.10
3DS      247.46
DC        15.97
DS       822.49
GB       255.45
GBA      318.50
GC       199.36
GEN       28.36
GG         0.04
N64      218.88
NES      251.07
NG         1.44
PC       258.82
PCFX       0.03
PS       730.66
PS2     1255.64
PS3      957.84
PS4      278.10
PSP      296.28
PSV       61.93
SAT       33.59
SCD        1.87
SNES     200.05
TG16       0.16
WS         1.42
Wii      926.71
WiiU      81.86
X360     979.96
XB       258.26
XOne     141.06
Name: Global_Sales, dtype: float64

<ipython-input-21-4a5528684683>:1: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  x1 = data.groupby('Platform')['Global_Sales'].transform(sum)

In [30]:
data['個平台銷售總合'] = x1
data

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,個平台銷售總合
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74,926.71
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,251.07
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82,926.71
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00,926.71
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,255.45
...,...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01,318.50
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01,199.36
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01,1255.64
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01,822.49
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01,318.50

In [35]:
data2 = data.copy()
global_sum = data2.groupby('Platform')['Global_Sales'].transform(np.sum)
data2['銷售佔比'] = data2['Global_Sales'] / global_sum
data2

<ipython-input-35-1e8cd648006c>:2: FutureWarning: The provided callable <function sum at 0x7cf16bdcbce0> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  global_sum = data2.groupby('Platform')['Global_Sales'].transform(np.sum)

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,個平台銷售總合,銷售佔比
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74,926.71,0.089284
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,251.07,0.160274
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82,926.71,0.038653
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00,926.71,0.035610
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,255.45,0.122803
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01,318.50,0.000031
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01,199.36,0.000050
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01,1255.64,0.000008
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01,822.49,0.000012
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01,318.50,0.000031

In [23]:
#使用apply來達成等同上面的功能
def rate(x):
    x['銷售佔比'] = x['Global_Sales'] / x['Global_Sales'].sum()
    return x
data2 = data.copy()
data2.groupby('Platform').apply(rate)

# 差異詳解: https://stackoverflow.com/questions/21828398/what-is-the-difference-between-pandas-agg-and-apply-function

<ipython-input-23-837fc39e2809>:6: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  data2.groupby('Platform').apply(rate)

                 Rank                      Name Platform    Year     Genre  \
Platform
2600     89        90                   Pac-Man     2600  1982.0    Puzzle
         239      240                  Pitfall!     2600  1981.0  Platform
         258      259                 Asteroids     2600  1980.0   Shooter
         544      545           Missile Command     2600  1980.0   Shooter
         607      608            Space Invaders     2600     NaN   Shooter
...               ...                       ...      ...     ...       ...
XOne     16530  16533  Sébastien Loeb Rally Evo     XOne  2016.0    Racing
         16531  16534             Hitman (2016)     XOne  2016.0    Action
         16562  16565              Mighty No. 9     XOne  2016.0  Platform
         16569  16572        Resident Evil 4 HD     XOne  2016.0   Shooter
         16576  16579         Rugby Challenge 3     XOne  2016.0    Sports

                           Publisher  NA_Sales  EU_Sales  JP_Sales  \
Platform
2600     89                    Atari      7.28      0.45       0.0
         239              Activision      4.21      0.24       0.0
         258                   Atari      4.00      0.26       0.0
         544                   Atari      2.56      0.17       0.0
         607                   Atari      2.36      0.14       0.0
...                              ...       ...       ...       ...
XOne     16530       Milestone S.r.l      0.00      0.01       0.0
         16531           Square Enix      0.00      0.01       0.0
         16562           Deep Silver      0.01      0.00       0.0
         16569                Capcom      0.01      0.00       0.0
         16576  Alternative Software      0.00      0.01       0.0

                Other_Sales  Global_Sales  個平台銷售總合      銷售佔比
Platform
2600     89            0.08          7.81    97.08  0.080449
         239           0.05          4.50    97.08  0.046354
         258           0.05          4.31    97.08  0.044396
         544           0.03          2.76    97.08  0.028430
         607           0.03          2.53    97.08  0.026061
...                     ...           ...      ...       ...
XOne     16530         0.00          0.01   141.06  0.000071
         16531         0.00          0.01   141.06  0.000071
         16562         0.00          0.01   141.06  0.000071
         16569         0.00          0.01   141.06  0.000071
         16576         0.00          0.01   141.06  0.000071

[16598 rows x 13 columns]

In [34]:
data2 = data.copy()
global_sum = data2.groupby('Platform')['Global_Sales'].aggregate(np.sum)  #會對不上, 要用transform
data2['銷售佔比'] = data2['Global_Sales'] / global_sum
data2

<ipython-input-34-8ab3c10ae0a5>:2: FutureWarning: The provided callable <function sum at 0x7cf16bdcbce0> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  global_sum = data2.groupby('Platform')['Global_Sales'].aggregate(np.sum)

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,個平台銷售總合,銷售佔比
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74,926.71,NaN
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,251.07,NaN
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82,926.71,NaN
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00,926.71,NaN
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,255.45,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01,318.50,NaN
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01,199.36,NaN
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01,1255.64,NaN
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01,822.49,NaN
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01,318.50,NaN

In [53]:
global_sum = data2.groupby('Platform').aggregate(sum)
global_sum['Global_Sales']

<ipython-input-53-319c83affd6b>:1: FutureWarning: The provided callable <built-in function sum> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  global_sum = data2.groupby('Platform').aggregate(sum)

Platform
2600      97.08
3DO        0.10
3DS      247.46
DC        15.97
DS       822.49
GB       255.45
GBA      318.50
GC       199.36
GEN       28.36
GG         0.04
N64      218.88
NES      251.07
NG         1.44
PC       258.82
PCFX       0.03
PS       730.66
PS2     1255.64
PS3      957.84
PS4      278.10
PSP      296.28
PSV       61.93
SAT       33.59
SCD        1.87
SNES     200.05
TG16       0.16
WS         1.42
Wii      926.71
WiiU      81.86
X360     979.96
XB       258.26
XOne     141.06
Name: Global_Sales, dtype: float64

In [58]:
global_sum = data2.groupby('Platform')['Global_Sales'].apply(sum)
global_sum

<ipython-input-58-34660946bd7a>:1: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
  global_sum = data2.groupby('Platform')['Global_Sales'].apply(sum)

Platform
2600      97.08
3DO        0.10
3DS      247.46
DC        15.97
DS       822.49
GB       255.45
GBA      318.50
GC       199.36
GEN       28.36
GG         0.04
N64      218.88
NES      251.07
NG         1.44
PC       258.82
PCFX       0.03
PS       730.66
PS2     1255.64
PS3      957.84
PS4      278.10
PSP      296.28
PSV       61.93
SAT       33.59
SCD        1.87
SNES     200.05
TG16       0.16
WS         1.42
Wii      926.71
WiiU      81.86
X360     979.96
XB       258.26
XOne     141.06
Name: Global_Sales, dtype: float64

In [62]:
data2.groupby('Platform').apply(rate)
data2
data['Global_Sales'].aggregate(sum)

<ipython-input-62-bfd5d42d451f>:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  data2.groupby('Platform').apply(rate)
<ipython-input-62-bfd5d42d451f>:3: FutureWarning: The provided callable <built-in function sum> is currently using Series.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  data['Global_Sales'].aggregate(sum)

8920.44

In [36]:
#fillter
# 列出所有PS平台的遊戲
def AAA(x):
    slist = ['PS','PS2','PS3']
    return any(x.iloc[0]['Platform'] in s for s in slist)
data.groupby('Platform').filter(AAA)

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,個平台銷售總合
16,17,Grand Theft Auto V,PS3,2013.0,Action,Take-Two Interactive,7.01,9.27,0.97,4.14,21.40,957.84
17,18,Grand Theft Auto: San Andreas,PS2,2004.0,Action,Take-Two Interactive,9.43,0.40,0.41,10.57,20.81,1255.64
24,25,Grand Theft Auto: Vice City,PS2,2002.0,Action,Take-Two Interactive,8.41,5.49,0.47,1.78,16.15,1255.64
28,29,Gran Turismo 3: A-Spec,PS2,2001.0,Racing,Sony Computer Entertainment,6.85,5.09,1.87,1.16,14.98,1255.64
34,35,Call of Duty: Black Ops II,PS3,2012.0,Shooter,Activision,4.99,5.88,0.65,2.52,14.03,957.84
...,...,...,...,...,...,...,...,...,...,...,...,...
16559,16562,Sugar + Spice! Anoko no Suteki na Nanimokamo,PS2,2008.0,Adventure,Alchemist,0.00,0.00,0.01,0.00,0.01,1255.64
16561,16564,Kanokon: Esuii,PS2,2008.0,Adventure,5pb,0.00,0.00,0.01,0.00,0.01,1255.64
16572,16575,Scarlett: Nichijou no Kyoukaisen,PS2,2008.0,Adventure,Kadokawa Shoten,0.00,0.00,0.01,0.00,0.01,1255.64
16580,16583,Real Rode,PS2,2008.0,Adventure,Kadokawa Shoten,0.00,0.00,0.01,0.00,0.01,1255.64
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01,1255.64